version: '2'
services:
    php:
      build: .
      depends_on:
        - mysql
      links:
        - mysql
      volumes:
          - ./html:/var/www/html
          - ./php-uploads.ini:/usr/local/etc/php/conf.d/php-uploads.ini
      ports:
          - 80:80
      restart: always

    apache:
      image: httpd:2.4
      ports:
          - 443:443
      links:
          - php
      restart: always

    mysql:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - "./.data/mysql:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_DATABASE: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker