version: '2'

services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     build: .
     volumes:
       - ./Wordpress/:/var/www/html
       - ./php-uploads.ini:/usr/local/etc/php/conf.d/php-uploads.ini
     links:
       - db
     ports:
       - "80:80"
     restart: always
